"""Initial migration. Schema matches specs/ exactly — enums, citext, bytea,
partial indexes, composite PKs. Written by hand rather than autogenerated so
the constraints are visible."""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ─── Extensions ───────────────────────────────────────────────────────────
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")   # gen_random_uuid()
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")     # case-insensitive email

    # ─── Enum types (created explicitly; models set create_type=False) ─────────
    op.execute("CREATE TYPE user_role AS ENUM ('software_developer','business_developer')")
    op.execute("CREATE TYPE connection_status AS ENUM ('pending','accepted','declined')")
    op.execute(
        "CREATE TYPE notification_type AS ENUM "
        "('connection_requested','connection_accepted','connection_declined',"
        "'new_message','idea_interest')"
    )
    op.execute(
        "CREATE TYPE idea_category AS ENUM "
        "('find_problem','build_product','design_brand','run_campaign','other')"
    )

    user_role = postgresql.ENUM(
        "software_developer", "business_developer", name="user_role", create_type=False
    )
    connection_status = postgresql.ENUM(
        "pending", "accepted", "declined", name="connection_status", create_type=False
    )
    notification_type = postgresql.ENUM(
        "connection_requested", "connection_accepted", "connection_declined",
        "new_message", "idea_interest", name="notification_type", create_type=False,
    )
    idea_category = postgresql.ENUM(
        "find_problem", "build_product", "design_brand", "run_campaign", "other",
        name="idea_category", create_type=False,
    )
    uuid = postgresql.UUID(as_uuid=True)

    # ─── users / sessions / magic links ──────────────────────────────────────
    op.create_table(
        "users",
        sa.Column("id", uuid, primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("email", postgresql.CITEXT, nullable=False, unique=True),
        sa.Column("password_hash", sa.Text, nullable=False),
        sa.Column("display_name", sa.String(80), nullable=False),
        sa.Column("first_name", sa.String(50), nullable=False),
        sa.Column("is_admin", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.text("true")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("last_login_at", sa.DateTime(timezone=True)),
        sa.Column("email_verified_at", sa.DateTime(timezone=True)),
        sa.CheckConstraint("char_length(display_name) BETWEEN 1 AND 80", name="ck_display_name_len"),
        sa.CheckConstraint("char_length(email) <= 254", name="ck_email_len"),
    )

    op.create_table(
        "sessions",
        sa.Column("id", uuid, primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", uuid, nullable=False),
        sa.Column("token_hash", sa.LargeBinary, nullable=False),
        sa.Column("csrf_token", sa.LargeBinary, nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_sessions_token_hash", "sessions", ["token_hash"], unique=True)
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"])
    op.create_index("ix_sessions_expires_at", "sessions", ["expires_at"])

    op.create_table(
        "magic_link_tokens",
        sa.Column("id", uuid, primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", uuid, nullable=False),
        sa.Column("token_hash", sa.LargeBinary, nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_magic_link_token_hash", "magic_link_tokens", ["token_hash"], unique=True)
    op.create_index("ix_magic_link_user_id", "magic_link_tokens", ["user_id"])

    # ─── reference data ───────────────────────────────────────────────────────
    op.create_table(
        "courses",
        sa.Column("id", uuid, primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("name", sa.String(100), nullable=False, unique=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_table(
        "skills",
        sa.Column("id", uuid, primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("name", sa.String(50), nullable=False, unique=True),
        sa.Column("category", sa.String(50)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_table(
        "interests",
        sa.Column("id", uuid, primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("name", sa.String(50), nullable=False, unique=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    # ─── photos / profiles ────────────────────────────────────────────────────
    op.create_table(
        "photos",
        sa.Column("id", uuid, primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", uuid, nullable=False),
        sa.Column("content_type", sa.String(50), nullable=False),
        sa.Column("byte_size", sa.Integer, nullable=False),
        sa.Column("data", sa.LargeBinary, nullable=False),   # bytea — ADR 0006
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint("byte_size > 0 AND byte_size <= 2097152", name="ck_photo_size"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_photos_user_id", "photos", ["user_id"], unique=True)

    op.create_table(
        "profiles",
        sa.Column("id", uuid, primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", uuid, nullable=False, unique=True),
        sa.Column("bio", sa.String(500)),
        sa.Column("role", user_role),
        sa.Column("course_id", uuid),
        sa.Column("looking_for", sa.String(300)),
        sa.Column("photo_id", uuid),
        sa.Column("profile_complete", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="SET NULL"),
    )

    # Composite PKs: the database enforces no-duplicates, not a SELECT-then-INSERT race.
    op.create_table(
        "profile_skills",
        sa.Column("profile_id", uuid, nullable=False),
        sa.Column("skill_id", uuid, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("profile_id", "skill_id"),
    )
    op.create_index("ix_profile_skills_skill_id", "profile_skills", ["skill_id"])

    op.create_table(
        "profile_interests",
        sa.Column("profile_id", uuid, nullable=False),
        sa.Column("interest_id", uuid, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["interest_id"], ["interests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("profile_id", "interest_id"),
    )
    op.create_index("ix_profile_interests_interest_id", "profile_interests", ["interest_id"])

    # ─── connection_requests ──────────────────────────────────────────────────
    op.create_table(
        "connection_requests",
        sa.Column("id", uuid, primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("sender_id", uuid, nullable=False),
        sa.Column("receiver_id", uuid, nullable=False),
        sa.Column("status", connection_status, nullable=False, server_default=sa.text("'pending'")),
        sa.Column("message", sa.String(300)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("responded_at", sa.DateTime(timezone=True)),
        sa.Column("responded_by", uuid),
        sa.Column("pair_lo", uuid, nullable=False),
        sa.Column("pair_hi", uuid, nullable=False),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["receiver_id"], ["users.id"], ondelete="CASCADE"),
        sa.CheckConstraint("sender_id <> receiver_id", name="ck_no_self_request"),
    )
    # One request per pair, both directions.
    op.create_index(
        "uq_one_request_per_pair", "connection_requests", ["pair_lo", "pair_hi"], unique=True
    )
    op.create_index("ix_connection_requests_received", "connection_requests", ["receiver_id", "status"])
    op.create_index("ix_connection_requests_sent", "connection_requests", ["sender_id", "status"])

    # ─── threads / messages / read cursors ────────────────────────────────────
    op.create_table(
        "threads",
        sa.Column("id", uuid, primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("connection_request_id", uuid, nullable=False, unique=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["connection_request_id"], ["connection_requests.id"], ondelete="CASCADE"),
    )
    op.create_table(
        "messages",
        sa.Column("id", uuid, primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("thread_id", uuid, nullable=False),
        sa.Column("sender_id", uuid, nullable=False),
        sa.Column("body", sa.Text, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="CASCADE"),
    )
    # Trailing id is the pagination tiebreaker — without it, messages sharing a
    # millisecond repeat across pages.
    op.create_index("ix_messages_thread_created_id", "messages", ["thread_id", "created_at", "id"])
    op.create_index("ix_messages_sender_id", "messages", ["sender_id"])

    op.create_table(
        "read_receipts",
        sa.Column("thread_id", uuid, nullable=False),
        sa.Column("user_id", uuid, nullable=False),
        sa.Column("last_read_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("thread_id", "user_id"),
    )

    # ─── notifications ────────────────────────────────────────────────────────
    op.create_table(
        "notifications",
        sa.Column("id", uuid, primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", uuid, nullable=False),
        sa.Column("type", notification_type, nullable=False),
        sa.Column("actor_id", uuid),
        sa.Column("connection_request_id", uuid),
        sa.Column("thread_id", uuid),
        sa.Column("project_idea_id", uuid),
        sa.Column("data", postgresql.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("url", sa.String(300), nullable=False, server_default=sa.text("'/notifications'")),
        sa.Column("read_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_notifications_user_read_created", "notifications", ["user_id", "read_at", "created_at"])
    # Partial index: unread is a small slice, and the bell counts it every load.
    op.create_index(
        "ix_notifications_unread",
        "notifications",
        ["user_id", "created_at"],
        postgresql_where=sa.text("read_at IS NULL"),
    )

    # ─── admin audit ──────────────────────────────────────────────────────────
    op.create_table(
        "admin_audit_log",
        sa.Column("id", uuid, primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("admin_id", uuid, nullable=False),
        sa.Column("action", sa.String(50), nullable=False),
        sa.Column("target_type", sa.String(50)),
        sa.Column("target_id", uuid),
        sa.Column("metadata", postgresql.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["admin_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_audit_created", "admin_audit_log", ["created_at"])
    op.create_index("ix_audit_admin_created", "admin_audit_log", ["admin_id", "created_at"])

    # ─── project ideas ────────────────────────────────────────────────────────
    op.create_table(
        "project_ideas",
        sa.Column("id", uuid, primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("author_id", uuid, nullable=False),
        sa.Column("title", sa.String(120), nullable=False),
        sa.Column("description", sa.Text, nullable=False),
        sa.Column("category", idea_category, nullable=False),
        # Free text, NOT a join to skills — specs/08 §2
        sa.Column("skills_needed", postgresql.ARRAY(sa.String), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("course_id", uuid),
        sa.Column("is_open", sa.Boolean, nullable=False, server_default=sa.text("true")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_project_ideas_created", "project_ideas", ["created_at"])
    op.create_index("ix_project_ideas_author", "project_ideas", ["author_id"])
    op.create_index("ix_project_ideas_open_created", "project_ideas", ["is_open", "created_at"])

    op.create_table(
        "idea_interests",
        sa.Column("idea_id", uuid, nullable=False),
        sa.Column("user_id", uuid, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["idea_id"], ["project_ideas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("idea_id", "user_id"),
    )
    op.create_index("ix_idea_interests_idea_id", "idea_interests", ["idea_id"])


def downgrade() -> None:
    for table in (
        "idea_interests", "project_ideas", "admin_audit_log", "notifications",
        "read_receipts", "messages", "threads", "connection_requests",
        "profile_interests", "profile_skills", "profiles", "photos",
        "interests", "skills", "courses",
        "magic_link_tokens", "sessions", "users",
    ):
        op.drop_table(table)
    op.execute("DROP TYPE IF EXISTS idea_category")
    op.execute("DROP TYPE IF EXISTS notification_type")
    op.execute("DROP TYPE IF EXISTS connection_status")
    op.execute("DROP TYPE IF EXISTS user_role")